config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tutorials, only:[:show, :index]
      resources :videos, only:[:show]
    end
  end

  root 'welcome#index'
  get 'tags/:tag', to: 'welcome#index', as: :tag
  get '/register', to: 'users#new'

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :tutorials, only: [:create, :edit, :update, :destroy, :new] do
      resources :videos, only: [:create]
    end
    resources :videos, only: [:edit, :update, :destroy]

    namespace :api do
      namespace :v1 do
        put "tutorial_sequencer/:tutorial_id", to: "tutorial_sequencer#update"
      end
    end
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'
  get '/about', to: 'about#show'
  get '/get_started', to: 'get_started#show'

  # email invite links to /sign_up for a new account
  get '/sign_up', to: 'users#new'

  get '/friendships/:login', to: 'friendships#create'

  resources :users, only: [:new, :create, :update, :edit]

  resources :tutorials, only: [:show, :index] do
    resources :videos, only: [:show, :index]
  end

  # oauth path
  get '/auth/:provider/callback', to: 'oauth#create'

  resources :user_videos, only:[:create, :destroy]

  get '/invite', to: 'github_invite#new', as: 'github_invite'
  post '/invite', to: 'github_invite#create'

  # url path for a user confirming email address
  get '/email_confirmation/:id', to: 'email_confirmation#edit', as: 'email_confirmation'
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

class Admin::DashboardController < Admin::BaseController
  def show
    @facade = AdminDashboardFacade.new
  end
end

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard</h1>
<h3>Tutorials</h3>

<div class="p2">
  <%= link_to "New Tutorial", new_admin_tutorial_path, class: "video-position-submit btn btn-outline" %>
</div>

<table class="col col-5">
  <tr>
    <th>Title</th>
    <th>Actions</th>
  </tr>
  <% @facade.tutorials.each do |tutorial| %>
    <tr class="admin-tutorial-card" id="<%= tutorial.id %>">
      <td><%= link_to tutorial.title, tutorial_path(tutorial) %></td>
      <td>
        <%= link_to "Edit", edit_admin_tutorial_path(tutorial) %> |
        <%= button_to 'Destroy', admin_tutorial_path(tutorial),
                              method: :delete,
                              data: { confirm: 'Are you sure?' }, id: 'link-btn' %>


      </td>
    </tr>
  <% end %>
</table>