config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tutorials, only:[:show, :index]
      resources :videos, only:[:show]
    end
  end

  root 'welcome#index'
  get 'tags/:tag', to: 'welcome#index', as: :tag
  get '/register', to: 'users#new'

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :tutorials, only: [:create, :edit, :update, :destroy, :new] do
      resources :videos, only: [:create]
    end
    resources :videos, only: [:edit, :update, :destroy]

    namespace :api do
      namespace :v1 do
        put "tutorial_sequencer/:tutorial_id", to: "tutorial_sequencer#update"
      end
    end
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'
  get '/about', to: 'about#show'
  get '/get_started', to: 'get_started#show'

  # email invite links to /sign_up for a new account
  get '/sign_up', to: 'users#new'

  get '/friendships/:login', to: 'friendships#create'

  resources :users, only: [:new, :create, :update, :edit]

  resources :tutorials, only: [:show, :index] do
    resources :videos, only: [:show, :index]
  end

  # oauth path
  get '/auth/:provider/callback', to: 'oauth#create'

  resources :user_videos, only:[:create, :destroy]

  get '/invite', to: 'github_invite#new', as: 'github_invite'
  post '/invite', to: 'github_invite#create'

  # url path for a user confirming email address
  get '/email_confirmation/:id', to: 'email_confirmation#edit', as: 'email_confirmation'
end

app/views/partials/_github.html.erb
<section class='github'>
  <h1>GitHub</h1>
  <h3 class='repos'>Repositories</h3>
  <% search_results.repos.each do |repo| %>
    <ul>
      <section class='repo'>
        <li><%= link_to repo.name, repo.svn_url %></li>
      </section>
    </ul>
  <% end %>
  <h3 class='followers'>Followers</h3>
  <% search_results.followers.each do |follower| %>
    <ul>
      <section class='follower' id='follower-<%= follower.login %>'>
        <li><%= link_to follower.login, follower.html_url %>
        <%= link_to 'Add Friend', "friendships/#{follower.login}", class: 'btn btn-primary mb1 bg-teal' if follower.friendable?(current_user) %></li>
      </section>
    </ul>
  <% end %>
  <h3 class='followings'>Following</h3>
  <% search_results.following.each do |user| %>
    <ul>
      <section class='following' id='following-<%= user.login %>'>
        <li><%= link_to user.login, user.html_url %>
        <%= link_to 'Add Friend', "friendships/#{user.login}", class: 'btn btn-primary mb1 bg-teal' if user.friendable?(current_user) %></li>
      </section>
    </ul>
  <% end %>
</section>

app/views/partials/_nav.html.erb
<nav class="primary_nav">
  <section class="left inner-nav table">
    <div class="logo align-middle table-cell">
      <%= link_to(image_tag('logo.png', class: "ml4", alt: "Turing Logo"), root_path) %>
    </div>
  </section>

  <section class="right links overflow-auto table mr4">

    <% if current_user %>
      <div class="align-middle table-cell p3">
        <%= link_to "Profile", dashboard_path %>
      </div>
      <% if current_user.admin? %>
      <div class="align-middle table-cell p3">
        <%= link_to "Admin", admin_dashboard_path %>
      </div>
      <% end %>
    <% else %>
      <div class="align-middle table-cell p3">
        <%= link_to 'Sign In', login_path, class: "px2"%>
        <%= link_to 'Register', register_path %>
      </div>
    <% end %>
  </section>
</nav>

app/views/partials/_search.html.erb
<div class="search-bar bar">
  <div class=" search-field col md-col-3">
    <%= form_tag(admin_video_path( ), method: :get, id: "search-form") do %>
      <%= text_field_tag :, params[:position], placeholder: "Search" %>
      <%= submit_tag "Search"  %>
    <% end %>
  </div>
  <div class="col md-col-9">
    <div class="category">
    </div>
  </div>
</div>

app/views/partials/_tools.html.erb
<div class="tool-bar bar">
  
</div>