config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tutorials, only:[:show, :index]
      resources :videos, only:[:show]
    end
  end

  root 'welcome#index'
  get 'tags/:tag', to: 'welcome#index', as: :tag
  get '/register', to: 'users#new'

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :tutorials, only: [:create, :edit, :update, :destroy, :new] do
      resources :videos, only: [:create]
    end
    resources :videos, only: [:edit, :update, :destroy]

    namespace :api do
      namespace :v1 do
        put "tutorial_sequencer/:tutorial_id", to: "tutorial_sequencer#update"
      end
    end
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'
  get '/about', to: 'about#show'
  get '/get_started', to: 'get_started#show'

  # email invite links to /sign_up for a new account
  get '/sign_up', to: 'users#new'

  get '/friendships/:login', to: 'friendships#create'

  resources :users, only: [:new, :create, :update, :edit]

  resources :tutorials, only: [:show, :index] do
    resources :videos, only: [:show, :index]
  end

  # oauth path
  get '/auth/:provider/callback', to: 'oauth#create'

  resources :user_videos, only:[:create, :destroy]

  get '/invite', to: 'github_invite#new', as: 'github_invite'
  post '/invite', to: 'github_invite#create'

  # url path for a user confirming email address
  get '/email_confirmation/:id', to: 'email_confirmation#edit', as: 'email_confirmation'
end

app/models/tutorial.rb
# frozen_string_literal: true

class Tutorial < ApplicationRecord
  validates_presence_of :title, :description, :thumbnail
  has_many :videos, -> { order(position: :ASC) }, dependent: :destroy
  acts_as_taggable_on :tags, :tag_list
  accepts_nested_attributes_for :videos
end

app/controllers/admin/tutorials_controller.rb
# frozen_string_literal: true

class Admin::TutorialsController < Admin::BaseController
  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  def create
    tutorial = Tutorial.new(tutorial_params)
    if tutorial.save
      flash[:notice] = 'Successfully created tutorial.'
      redirect_to tutorial_path(tutorial)
    else
      flash[:error] = tutorial.errors.full_messages.to_sentence
      redirect_to new_admin_tutorial_path
    end
  end

  def new
    @tutorial = Tutorial.new
  end

  def update
    tutorial = Tutorial.find(params[:id])
    flash[:success] = "#{tutorial.title} tagged!" if tutorial.update(tag_params)
    redirect_to edit_admin_tutorial_path(tutorial)
  end

  def destroy
    Tutorial.destroy(params[:id])
    redirect_to admin_dashboard_path
  end

  private

  def tag_params
    params.require(:tutorial).permit(:tag_list)
  end

  def tutorial_params
    params.require(:tutorial).permit(:title, :description, :thumbnail, :playlist_id, :classroom)
  end
end

app/controllers/api/v1/tutorials_controller.rb
# frozen_string_literal: true

class Api::V1::TutorialsController < ApplicationController
  def index
    render json: Tutorial.all
  end

  def show
    render json: Tutorial.find(params[:id])
  end
end

app/controllers/tutorials_controller.rb
# frozen_string_literal: true

class TutorialsController < ApplicationController
  before_action :user_authentication, only: :show

  def show
    @facade = TutorialFacade.new(tutorial, params[:video_id])
  end

  private

  def user_authentication
    if tutorial.classroom && !current_user
      flash.now[:error] = 'User must login to view classroom tutorials'
      render file: "#{Rails.root}/public/404.html", status: 404
    end
  end

  def tutorial
    @tutorial ||= Tutorial.find(params[:id])
  end
end

app/views/tutorials/index.html.erb
<main class="tutorials">
  <% @tutorials.each do |tutorial| %>
  <section class="tutorial">
    <div class="tutorial-thumbnail col md-col-2">
      <a>
        <img class"thumbnail" src= <%= "#{tutorial.thumbnail}" %> alt="">
      </a>
    </div>

    <div class="tutorial-description col md-col-10">
      <%= link_to tutorial.title, tutorial_path(tutorial) %>
      <p> <%= tutorial.description %> </p>
    </div>
  </section>
  <% end %>
</main>

app/views/tutorials/show.html.erb
<main class="tutorials">
<h2><%= @facade.title %></h2>
<h1 id="message"></h1>
<div class="col col-4">

  <% if @facade.videos.empty? %>

    <h4>Videos (<%= @facade.videos.count %>)</h4>
    <p>There are no videos in this tutorial.</p>

    <% if current_user && current_user.admin? %>
      <div data-controller="tutorials">
        <%= link_to "Add Video", "#", "data-action" => "click->tutorials#showVideoForm", class: "video-position-submit btn btn-outline", id: @facade.id %>
      </div>

      <div class="mt1" id="new-video-form">
        <h3>New Video</h3>
        <%= form_for [:admin, @facade, Video.new] do |f| %>
          <%= f.label :title, class: "block" %>
          <%= f.text_field :title, class: "field block"%>
          <%= f.label :description, class: "block" %>
          <%= f.text_field :description, class: "field block"%>
          <%= f.label "YoutTube ID", class: "block" %>
          <%= f.text_field :video_id, class: "field block"%>

          <%= f.submit "Create Video", class: "mt1 btn btn-outline"  %>
        <% end %>
      </div>
    </div>
    <% end %>

  <% else %>

    <h4>Videos</h4>
    <ul>
      <% @facade.videos.each do |video| %>
        <li>
          <h3><%= link_to video.title, tutorial_path(video_id: video.id), class: "show-link", id: video.position %></h3>
        </li>
      <% end %>
    </ul>

      <div class="col col-8">
        <div class="title-bookmark">
          <h3><%= @facade.current_video.title %></h3>
          <div class="bookmarks-btn">
            <% if current_user %>
              <%= button_to "Bookmark", user_videos_path(video_id: @facade.current_video.id, user_id: current_user.id), method: :post, class: "btn btn-outline mb1 teal" %>
            <% else %>
              <div class="tooltip">Bookmark
                  <span class="tooltiptext">Please log in or register to bookmark videos</span>
              </div>
            <% end %>
          </div>
        </div>

        <div id="player">
          <script src="https://www.youtube.com/player_api"></script>
          <script>
          // create youtube player
          var player;
          var position;
          function onYouTubePlayerAPIReady() {
            player = new YT.Player('player', {
              width: '640',
              height: '390',
              videoId: '<%= @facade.current_video.video_id %>',
              events: {
                onReady: onPlayerReady,
                onStateChange: onPlayerStateChange
              }
            });
          }

        // autoplay video
        function onPlayerReady(event) {
          event.target.playVideo();
        }

        // when video ends
        function onPlayerStateChange(event) {
          if(event.data === 0 && <%= @facade.play_next_video? %>) {
            window.location = "/tutorials/<%=@facade.id%>?video_id=<%=@facade.next_video.id %>";
          } else if(event.data === 0 && <%= @facade.play_next_video? == false %>) {
            const message = document.querySelector(`#message`);
            message.innerHTML = "You watched them all. Bask in the glory of your new skills."
          }
        }
        </script>
      </div>

      <h4>Description</h4>
        <p data-controller="tutorials" id="description-<%= @facade.current_video.id %>">
          <%= @facade.current_video.description.truncate(50) %>...
          <%= link_to "More", "#", "data-action" => "click->tutorials#showDescription", id: @facade.current_video.id, class: "show-link"%>
        </p>
      </div>
    <% end %>
</main>