config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tutorials, only:[:show, :index]
      resources :videos, only:[:show]
    end
  end

  root 'welcome#index'
  get 'tags/:tag', to: 'welcome#index', as: :tag
  get '/register', to: 'users#new'

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :tutorials, only: [:create, :edit, :update, :destroy, :new] do
      resources :videos, only: [:create]
    end
    resources :videos, only: [:edit, :update, :destroy]

    namespace :api do
      namespace :v1 do
        put "tutorial_sequencer/:tutorial_id", to: "tutorial_sequencer#update"
      end
    end
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/dashboard', to: 'users#show'
  get '/about', to: 'about#show'
  get '/get_started', to: 'get_started#show'

  # email invite links to /sign_up for a new account
  get '/sign_up', to: 'users#new'

  get '/friendships/:login', to: 'friendships#create'

  resources :users, only: [:new, :create, :update, :edit]

  resources :tutorials, only: [:show, :index] do
    resources :videos, only: [:show, :index]
  end

  # oauth path
  get '/auth/:provider/callback', to: 'oauth#create'

  resources :user_videos, only:[:create, :destroy]

  get '/invite', to: 'github_invite#new', as: 'github_invite'
  post '/invite', to: 'github_invite#create'

  # url path for a user confirming email address
  get '/email_confirmation/:id', to: 'email_confirmation#edit', as: 'email_confirmation'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    if current_user
      user_tutorials
    else
      visitor_tutorials
    end
  end

  private

  def user_tutorials
    if params[:tag]
      @tutorials = Tutorial.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 5)
    else
      @tutorials = Tutorial.all.paginate(page: params[:page], per_page: 5)
    end
  end

  def visitor_tutorials
    if params[:tag]
      @tutorials = Tutorial.where(classroom: false).tagged_with(params[:tag]).paginate(page: params[:page], per_page: 5)
    else
      @tutorials = Tutorial.where(classroom: false).paginate(page: params[:page], per_page: 5)
    end
  end
end

app/views/welcome/index.html.erb
<div class="home-page-title">
  <h1>Video Tutorials</h1>
  <hr>
</div>
<section class="tutorials col md-col-8">
  <% @tutorials.each do |tutorial| %>
    <div class="tutorial">
      <img class="thumbnail col md-col-3" src= <%="#{tutorial.thumbnail}" %> >
      <div class="tutorial-description col md-col-9">
        <h4 class="tutorial-title-home"><%= link_to tutorial.title, tutorial_path(tutorial), class: "title-link" %> </h4>
        <p class="description"><%= tutorial.description %></p> <br>
      </div>
    </div> <br>
  <% end %>
  <hr>
  <br>
  <div class="paginater">
    <%= will_paginate @tutorials %>
  </div>
</section>
<aside class="categories col md-col-4">
  <h1>Filters:</h1>
  <hr>
  <div class="tags">
    <% tag_cloud Tutorial.tag_counts, %w[.m] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: "btn btn-primary mb1 bg-teal"  %>
    <% end %>
  </div>
  <hr>
  <%= link_to "Reset", root_path, class: "btn btn-outline mb1 aqua"  %>
</aside>